// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// dmvnInt
arma::vec dmvnInt(const arma::mat& X, const arma::rowvec& mu, const arma::mat& L);
RcppExport SEXP _lr_dmvnInt(SEXP XSEXP, SEXP muSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(dmvnInt(X, mu, L));
    return rcpp_result_gen;
END_RCPP
}
// lm_qr
arma::vec lm_qr(const arma::mat& X, const arma::vec& y);
RcppExport SEXP _lr_lm_qr(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(lm_qr(X, y));
    return rcpp_result_gen;
END_RCPP
}
// lm_local_pred
double lm_local_pred(const arma::vec& y, const arma::rowvec& x0, const arma::rowvec& X0, const arma::mat& x, const arma::mat& X, const arma::mat& L);
RcppExport SEXP _lr_lm_local_pred(SEXP ySEXP, SEXP x0SEXP, SEXP X0SEXP, SEXP xSEXP, SEXP XSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(lm_local_pred(y, x0, X0, x, X, L));
    return rcpp_result_gen;
END_RCPP
}
// get_chol
arma::mat get_chol(arma::mat& H);
RcppExport SEXP _lr_get_chol(SEXP HSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type H(HSEXP);
    rcpp_result_gen = Rcpp::wrap(get_chol(H));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lr_dmvnInt", (DL_FUNC) &_lr_dmvnInt, 3},
    {"_lr_lm_qr", (DL_FUNC) &_lr_lm_qr, 2},
    {"_lr_lm_local_pred", (DL_FUNC) &_lr_lm_local_pred, 6},
    {"_lr_get_chol", (DL_FUNC) &_lr_get_chol, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_lr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
