# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmvnInt <- function(X, mu, L) {
    .Call(`_lr_dmvnInt`, X, mu, L)
}

lm_qr_rcpp <- function(X, y) {
    .Call(`_lr_lm_qr_rcpp`, X, y)
}

lm_ch_rcpp <- function(X, y) {
    .Call(`_lr_lm_ch_rcpp`, X, y)
}

lm_local_reg <- function(y, x0, X0, x, X, L) {
    .Call(`_lr_lm_local_reg`, y, x0, X0, x, X, L)
}

lm_local_reg_iter <- function(y, x0, X0, x, X, L) {
    .Call(`_lr_lm_local_reg_iter`, y, x0, X0, x, X, L)
}

get_chol <- function(H) {
    .Call(`_lr_get_chol`, H)
}

