# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Train a local least regression model and make predictions at multiple points
#' This iterates over the data and call lm_local_pred
#' @param y arma::vec - outcomes of the data
#' @param x0 arma::vec - rows are points to make predictions at
#' @param X0 arma::mat - feature transform of rows of X0
#' @param x arma::mat - rows are samples from the data
#' @param X arma::mat - feature transform's of rows of x
#' @param L arma::mat - Lower Cholesky matrix of the bandwidth matrix
NULL

#' Evaluates the mutltivariate normal density function
#' @param X arma::mat - rows will be evaluated by the normal density function
#' @param mu arma::vec- mean of the distribution
#' @param L arma::mat - lower cholesky matrix of the bandwidth matrix H
dmvnInt <- function(X, mu, L) {
    .Call(`_lr_dmvnInt`, X, mu, L)
}

#' Computes the least square parameters using QR decomposition
#' @param X arma::mat - rows are samples from the data
#' @param y arma::mat - outcomes corresponding to the rows of X
#' @return parameters of the least squares estimator
lm_qr <- function(X, y) {
    .Call(`_lr_lm_qr`, X, y)
}

#' Train a local least regression model and make a prediction at a single point
#' @param y arma::vec - outcomes of the data
#' @param x0 arma::vec- the point to make a prediction at
#' @param X0 arma::vec - feature transform of x0
#' @param x arma::mat - rows are samples from the data
#' @param X arma::mat - feature transform's of rows of x
#' @param L arma::mat - Lower Cholesky matrix of the bandwidth matrix
lm_local_pred <- function(y, x0, X0, x, X, L) {
    .Call(`_lr_lm_local_pred`, y, x0, X0, x, X, L)
}

#' Get the lower cholesky decomposition of  a matrix
#' @param H matrix - the matrix to perform cholesky decomposition on
#' @return Lower cholesky matrix of H
get_chol <- function(H) {
    .Call(`_lr_get_chol`, H)
}

